services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://todouser:todopass@postgres:5432/tododb
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: todouser
      DB_PASSWORD: todopass
      DB_NAME: tododb
    depends_on:
      - postgres         

  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: