services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://todouser:todopass@postgres:5432/tododb
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: todouser
      DB_PASSWORD: todopass
      DB_NAME: tododb
    depends_on:
      postgres:
        condition: service_healthy   # <-- আসল সমাধান
    restart: unless-stopped
    networks:
      - todonet

  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d tododb"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - todonet

  prometheus:
    image: prom/prometheus:latest
    container_name: todo_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - promdata:/prometheus
    depends_on:
      - app
    networks:
      - todonet

  grafana:
    image: grafana/grafana:latest
    container_name: todo_grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - todonet

volumes:
  pgdata:
  promdata:
  grafanadata:

networks:
  todonet:
    driver: bridge